version: '3.3'
services:
  lb:
    image: lb
    build:
      context: .
      dockerfile: Dockerfile.lb
    ports:
      - "4000:4000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./script.mjs:/etc/nginx/script.mjs:ro
  pool:
    image: hello
    build:
      context: .
      dockerfile: Dockerfile.hello
    deploy:
      replicas: 2

